from setuptools import setup

APP = ['content_generator.py']
OPTIONS = {
    'argv_emulation': True,
    'packages': ['tkinter', 'PIL', 'requests', 'bs4'],
    'includes': ['pytesseract', 'pyperclip'],
}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['content_generator.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
